//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelerikMauiShellApp1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TelerikMauiShellApp1.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More....
        /// </summary>
        internal static string APPOINT_CAL_MORE {
            get {
                return ResourceManager.GetString("APPOINT_CAL_MORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        internal static string CAL_FILTER_EVENTSTATUS_CONFIRMED {
            get {
                return ResourceManager.GetString("CAL_FILTER_EVENTSTATUS_CONFIRMED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temporary.
        /// </summary>
        internal static string CAL_FILTER_EVENTSTATUS_TEMPORARY {
            get {
                return ResourceManager.GetString("CAL_FILTER_EVENTSTATUS_TEMPORARY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under planning.
        /// </summary>
        internal static string CAL_FILTER_EVENTSTATUS_UNDERPLANNING {
            get {
                return ResourceManager.GetString("CAL_FILTER_EVENTSTATUS_UNDERPLANNING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3 days.
        /// </summary>
        internal static string CALENDAR_VIEW_CUSTOM_DAYS {
            get {
                return ResourceManager.GetString("CALENDAR_VIEW_CUSTOM_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string CALENDAR_VIEW_DAY {
            get {
                return ResourceManager.GetString("CALENDAR_VIEW_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string CALENDAR_VIEW_MONTH {
            get {
                return ResourceManager.GetString("CALENDAR_VIEW_MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        internal static string CALENDAR_VIEW_WEEK {
            get {
                return ResourceManager.GetString("CALENDAR_VIEW_WEEK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence.
        /// </summary>
        internal static string TID_TYPE_ABSENCE {
            get {
                return ResourceManager.GetString("TID_TYPE_ABSENCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Present.
        /// </summary>
        internal static string TID_TYPE_PRESENT {
            get {
                return ResourceManager.GetString("TID_TYPE_PRESENT", resourceCulture);
            }
        }
    }
}
